FROM bh9fxk/openwebrx-base:dev-latest

LABEL description="OpenWebRX + Digital codecs (mbelib), using codecserver-softmbe."

COPY docker/scripts/install-dependencies-*.sh \
     docker/files/sdrplay/install-lib.*.patch \
     docker/scripts/install-connectors.sh /

RUN /install-dependencies-rtlsdr.sh &&\
    /install-dependencies-soapysdr.sh &&\
    /install-dependencies-hackrf.sh &&\
    /install-dependencies-sdrplay.sh &&\
    /install-dependencies-airspy.sh &&\
    /install-dependencies-afedri.sh &&\
    /install-dependencies-rtlsdr-soapy.sh &&\
    /install-dependencies-plutosdr.sh &&\
    /install-dependencies-limesdr.sh &&\
    /install-dependencies-soapyremote.sh &&\
    /install-dependencies-perseus.sh &&\
    /install-dependencies-fcdpp.sh &&\
    /install-dependencies-radioberry.sh &&\
    /install-dependencies-uhd.sh &&\
    /install-dependencies-hpsdr.sh &&\
    /install-dependencies-bladerf.sh &&\
    /install-connectors.sh &&\
    /install-dependencies-runds.sh &&\
    rm /install-dependencies-*.sh &&\
    rm /install-lib.*.patch && \
    rm /install-connectors.sh

# insatall softmbe
COPY docker/scripts/integrate-softmbe-dev.sh /
RUN chmod +x /integrate-softmbe-dev.sh && \
    /integrate-softmbe-dev.sh && \
    rm /integrate-softmbe-dev.sh

# 精简镜像
RUN rm -rf /usr/share/doc/* /usr/share/man/* /var/cache/*
RUN rm -rf \
    /etc/cron.* \
    /etc/logrotate.d \
    /var/log/* \
    /var/lib/apt/lists/* \
    /usr/share/locale/* \
    /usr/share/i18n/* \
    /usr/share/zoneinfo/* || true \
    && find /usr/share/doc -depth -type f ! -name copyright -exec rm {} + \
    && find /usr/share/man -type f -exec rm -f {} + \
    && rm -rf /root/.cache

COPY docker/files/services/sdrplay /etc/services.d/sdrplay

ADD . /opt/openwebrx
