FROM debian:bookworm-slim

COPY docker/files/js8call/js8call-hamlib.patch \
     docker/files/wsjtx/wsjtx.patch \
     docker/files/wsjtx/wsjtx-hamlib.patch \
     docker/files/dream/dream.patch \
     docker/files/direwolf/direwolf-hamlib.patch \
     docker/scripts/install-dependencies.sh /
RUN /install-dependencies.sh && \
    rm /install-dependencies.sh && \
    rm /*.patch
COPY docker/scripts/integrate-softmbe-dev.sh /
RUN chmod +x /integrate-softmbe-dev.sh && \
    rm /integrate-softmbe-dev.sh
COPY docker/scripts/install-owrx-tools.sh /
RUN /install-owrx-tools.sh && \
    rm /install-owrx-tools.sh

COPY docker/scripts/install-dependencies-*.sh \
     docker/files/sdrplay/install-lib.*.patch \
     docker/scripts/install-connectors.sh /

RUN /install-dependencies-rtlsdr.sh &&\
    /install-dependencies-soapysdr.sh &&\
    /install-dependencies-hackrf.sh &&\
    /install-dependencies-sdrplay.sh &&\
    /install-dependencies-airspy.sh &&\
    /install-dependencies-afedri.sh &&\
    /install-dependencies-rtlsdr-soapy.sh &&\
    /install-dependencies-plutosdr.sh &&\
    /install-dependencies-limesdr.sh &&\
    /install-dependencies-soapyremote.sh &&\
    /install-dependencies-perseus.sh &&\
    /install-dependencies-fcdpp.sh &&\
    /install-dependencies-radioberry.sh &&\
    /install-dependencies-uhd.sh &&\
    /install-dependencies-hpsdr.sh &&\
    /install-dependencies-bladerf.sh &&\
    /install-connectors.sh &&\
    /install-dependencies-runds.sh &&\
    rm /install-dependencies-*.sh &&\
    rm /install-lib.*.patch && \
    rm /install-connectors.sh

COPY docker/files/services/codecserver /etc/services.d/codecserver

COPY docker/files/services/sdrplay /etc/services.d/sdrplay

ADD . /opt/openwebrx

ENTRYPOINT ["/init"]

WORKDIR /opt/openwebrx

VOLUME /etc/openwebrx
VOLUME /var/lib/openwebrx

ENV S6_CMD_ARG0="/opt/openwebrx/docker/scripts/run.sh"
CMD [""]

EXPOSE 8073

